name: CD API Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  cd-api-firebase-functions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
        working-directory: ./functions
      - run: npm run lint
        working-directory: ./functions
      - run: npm run build
        working-directory: ./functions
      - run: npx firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
        working-directory: ./functions
        env:
          CI: true
