name: CD NodeList Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  cd-node-list-firebase-hosting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run build --if-present
      - run: npm i -g firebase-tools typescript
      - run: npx firebase deploy --only hosting:node-list --token ${{ secrets.FIREBASE_TOKEN }}
